name: GitHub-Script (by PSModule)
description: A GitHub Action used for running a PowerShell Script that uses the GitHub PowerShell module
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  working-directory:
    description: The working directory where the script will run from
    required: false
  script:
    description: The script to run
    required: true

runs:
  using: composite
  steps:
    - name: Install GitHub
      shell: pwsh
      run: |
        # Install GitHub
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose

    - name: GitHub-Script
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ inputs.script }}
