name: GitHub-Script (by PSModule)
description: A GitHub Action used for running a PowerShell script that uses the GitHub PowerShell module
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  Script:
    description: The script to run. Can be inline, multi-line or a path to a script file.
    required: false
  Token:
    description: Log in using an Installation Access Token (IAT).
    required: false
    default: ${{ github.token }}
  ClientID:
    description: Log in using a GitHub App, using the App's Client ID and Private Key.
    required: false
  PrivateKey:
    description: Log in using a GitHub App, using the App's Client ID and Private Key.
    required: false
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  ShowOutput:
    description: Show the output of the script.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: ${{ github.workspace }}

outputs:
  result:
    description: The output of the script as a JSON object. To add outputs to `result`, use `Set-GitHubOutput`.
    value: ${{ steps.RunGitHubScript.outputs.result }}

runs:
  using: composite
  steps:
    - name: Install GitHub
      shell: pwsh
      id: RunGitHubScript
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        GITHUB_ACTION_INPUT_Token: ${{ inputs.Token }}
        GITHUB_ACTION_INPUT_ClientID: ${{ inputs.ClientID }}
        GITHUB_ACTION_INPUT_PrivateKey: ${{ inputs.PrivateKey }}
        GITHUB_ACTION_INPUT_Debug: ${{ inputs.Debug }}
        GITHUB_ACTION_INPUT_Verbose: ${{ inputs.Verbose }}
        GITHUB_ACTION_INPUT_Version: ${{ inputs.Version }}
        GITHUB_ACTION_INPUT_ShowOutput: ${{ inputs.ShowOutput }}
        GITHUB_ACTION_INPUT_Prerelease: ${{ inputs.Prerelease }}
      run: |
        # GitHub-Script
        . $(Join-Path -Path '${{ github.action_path }}' -ChildPath 'scripts\main.ps1'
        ${{ inputs.Script }}
        . $(Join-Path -Path '${{ github.action_path }}' -ChildPath 'scripts\outputs.ps1'
