name: GitHub-Script (by PSModule)
description: A GitHub Action used for running a PowerShell Script that uses the GitHub PowerShell module
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  working-directory:
    description: The working directory where the script will run from
    required: false
  script:
    description: The script to run
    required: true
  token:
    description: The GitHub token to use
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Install GitHub
      shell: pwsh
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        # Install GitHub
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" -Verbose
        ${{ inputs.script }}
