Write-Host "Cleaning up..."
Write-Host "LASTEXITCODE: $LASTEXITCODE"
Write-Host "PSMODULE_GITHUB_SCRIPT: $env:PSMODULE_GITHUB_SCRIPT"
$env:PSMODULE_GITHUB_SCRIPT = $false
Write-Host "PSMODULE_GITHUB_SCRIPT: $env:PSMODULE_GITHUB_SCRIPT"
