on:
  workflow_call:
    inputs:
      runs-on:
        description: The operating system to run the tests on
        required: true
        type: string
      Prerelease:
        description: Run the prerelease version of the action
        required: false
        type: boolean
        default: false
    secrets:
      TEST_USER_PAT:
        description: Personal Access Token for the test user
        required: true
      TEST_USER_USER_FG_PAT:
        description: Personal Access Token for the test user with full gists scope
        required: true
      TEST_USER_ORG_FG_PAT:
        description: Personal Access Token for the test user with full gists scope
        required: true
      TEST_APP_ENT_CLIENT_ID:
        description: Client ID for the test GitHub App for the enterprise
        required: true
      TEST_APP_ENT_PRIVATE_KEY:
        description: Private Key for the test GitHub App for the enterprise
        required: true
      TEST_APP_ORG_CLIENT_ID:
        description: Client ID for the test GitHub App for the organization
        required: true
      TEST_APP_ORG_PRIVATE_KEY:
        description: Private Key for the test GitHub App for the organization
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ActionTestCommands:
    name: Commands + Outputs
    runs-on: ${{ inputs.runs-on }}
    outputs:
      MatrixTest: ${{ fromJson(steps.test.outputs.result).MatrixTest }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        id: test
        with:
          Name: Action-Test
          Debug: true
          Verbose: true
          Prerelease: ${{ inputs.Prerelease }}
          ShowInit: true
          ShowOutput: true
          Script: |
            LogGroup "Get header from Get-GitHubUser" {
                $results = Invoke-GithubAPI -APIEndpoint "/user" -Debug -Verbose
                $headers = $results.headers
                Write-Host "$($headers | Format-List | Out-String)"
            }
