on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The operating system to run the tests on'
        required: true
        type: string
    secrets:
      TEST_USER_PAT:
        description: 'Personal Access Token for the test user'
        required: true
      TEST_USER_USER_FG_PAT:
        description: 'Personal Access Token for the test user with full gists scope'
        required: true
      TEST_USER_ORG_FG_PAT:
        description: 'Personal Access Token for the test user with full gists scope'
        required: true
      TEST_APP_ENT_CLIENT_ID:
        description: 'Client ID for the test GitHub App for the enterprise'
        required: true
      TEST_APP_ENT_PRIVATE_KEY:
        description: 'Private Key for the test GitHub App for the enterprise'
        required: true
      TEST_APP_ORG_CLIENT_ID:
        description: 'Client ID for the test GitHub App for the organization'
        required: true
      TEST_APP_ORG_PRIVATE_KEY:
        description: 'Private Key for the test GitHub App for the organization'
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ActionTestBasic:
    name: Action-Test - [Basic] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          Debug: true
          Verbose: true

  ActionTestWithScript:
    name: Action-Test - [WithScript] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          Debug: true
          Verbose: true
          Script: |
            LogGroup 'Get-GitHubZen' {
              Get-GitHubZen
            }

            LogGroup 'Get-GitHubViewer' {
              Get-GitHubViewer -Fields name, login, id, databaseID
            }

  ActionTestCommands:
    name: Action-Test - [Commands] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        id: test
        with:
          Debug: true
          Verbose: true
          Prerelease: true
          ShowOutput: true
          Script: |
            $cat = Get-GitHubOctocat
            $zen = Get-GitHubZen
            Set-GitHubEnvironmentVariable -Name 'OCTOCAT' -Value $cat
            Set-GitHubOutput -Name 'WISECAT' -Value $cat
            Set-GitHubOutput -Name 'Zen' -Value $zen

      - name: Run-test
        shell: pwsh
        env:
          result: ${{ steps.test.outputs.result }}
          WISECAT: ${{ fromJson(steps.test.outputs.result).WISECAT }}
        run: |
          $result = $env:result | ConvertFrom-Json
          Set-GitHubStepSummary -Summary $env:WISECAT
          Write-GitHubNotice -Message $result.Zen -Title 'GitHub Zen'

  ActionTestWithoutToken:
    name: Action-Test - [WithoutToken] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          Token: ''
          Script: |
            LogGroup 'My group' {
              'This is a group'
            }

  ActionTestWithPAT:
    name: Action-Test - [WithPAT] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          Token: ${{ secrets.TEST_USER_PAT }}
          Script: |
            LogGroup 'Get-GitHubUser' {
              Get-GitHubUser | Format-Table -AutoSize
            }

  ActionTestWithUSERFGPAT:
    name: Action-Test - [WithUserFGPAT] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          Token: ${{ secrets.TEST_USER_USER_FG_PAT }}
          Script: |
            LogGroup 'Get-GitHubUser' {
              Get-GitHubUser | Format-Table -AutoSize
            }

  ActionTestWithORGFGPAT:
    name: Action-Test - [WithOrgFGPAT] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          Token: ${{ secrets.TEST_USER_ORG_FG_PAT }}
          Script: |
            LogGroup 'Get-GitHubUser' {
              Get-GitHubUser | Format-Table -AutoSize
            }

  ActionTestWithGitHubAppEnt:
    name: Action-Test - [GitHubAppEnt] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          ClientID: ${{ secrets.TEST_APP_ENT_CLIENT_ID }}
          PrivateKey: ${{ secrets.TEST_APP_ENT_PRIVATE_KEY }}
          Script: |
            LogGroup 'Get-GitHubApp' {
              Get-GitHubApp | Format-Table -AutoSize
            }

            LogGroup 'Get-GitHubAppInstallation' {
              Get-GitHubAppInstallation | Format-Table -AutoSize
            }

            LogGroup 'Do something as an installation' {
              Get-GithubAppInstallation | New-GitHubAppInstallationAccessToken | ForEach-Object {
                Connect-GitHub -Token $_.token -Silent
                Get-GitHubContext | Format-Table -AutoSize
                Get-GitHubGitConfig | Format-Table -AutoSize
              }
            }

  ActionTestWithGitHubAppOrg:
    name: Action-Test - [GitHubAppOrg] - [${{ inputs.runs-on }}]
    runs-on: ${{ inputs.runs-on }}
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        uses: ./
        with:
          ClientID: ${{ secrets.TEST_APP_ORG_CLIENT_ID }}
          PrivateKey: ${{ secrets.TEST_APP_ORG_PRIVATE_KEY }}
          Script: |
            LogGroup 'Get-GitHubApp' {
              Get-GitHubApp | Format-Table -AutoSize
            }

            LogGroup 'Get-GitHubAppInstallation' {
              Get-GitHubAppInstallation | Format-Table -AutoSize
            }

            LogGroup 'Do something as an installation' {
              Get-GithubAppInstallation | New-GitHubAppInstallationAccessToken | ForEach-Object {
                Connect-GitHub -Token $_.token -Silent
                Get-GitHubContext | Format-Table -AutoSize
                Get-GitHubGitConfig | Format-Table -AutoSize
              }
            }
